"""Constante pentru Info Meteo Romania."""

DOMAIN = "info_meteo_romania"
SCAN_INTERVAL = 30  # minute

# URL-uri API ANM
WEATHER_API_URL = "https://www.meteoromania.ro/wp-json/meteoapi/v2/starea-vremii"
ALERTS_XML_URL = "https://www.meteoromania.ro/avertizari-xml.php"
NOWCASTING_XML_URL = "https://www.meteoromania.ro/avertizari-nowcasting-xml.php"

# URL Open-Meteo pentru prognoza zilnica (gratuit, fara API key)
FORECAST_API_URL = "https://api.open-meteo.com/v1/forecast?latitude={lat}&longitude={lon}&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max,weathercode,windspeed_10m_max&timezone=Europe%2FBucharest&forecast_days=7"

# Cheia = ce vede utilizatorul in meniu
# Valoarea = (nume exact API ANM, latitudine, longitudine)
CITIES = {
    "Adamclisi": ("ADAMCLISI", 43.99, 28.18),
    "Adjud": ("ADJUD", 46.10, 27.17),
    "Alba Iulia": ("ALBA IULIA", 46.07, 23.58),
    "Alexandria": ("ALEXANDRIA", 43.97, 25.33),
    "Amzacea": ("AMZACEA", 43.87, 28.32),
    "Arad": ("ARAD", 46.17, 21.32),
    "Bacău": ("BACAU", 46.57, 26.92),
    "Bacles": ("BACLES", 44.70, 23.43),
    "Baia Mare": ("BAIA MARE", 47.65, 23.58),
    "Băile Herculane": ("BAILE HERCULANE", 44.87, 22.41),
    "Băilești": ("BAILESTI", 44.02, 23.35),
    "Băișoara": ("BAISOARA", 46.55, 23.37),
    "Balea Lac": ("BALEA LAC", 45.60, 24.62),
    "Banloc": ("BANLOC", 45.37, 21.07),
    "Baraolt": ("BARAOLT", 46.07, 25.60),
    "Bârlad": ("BARLAD", 46.23, 27.67),
    "Barnova": ("BARNOVA (RADAR)", 47.07, 27.47),
    "Batoș": ("BATOS", 46.93, 24.70),
    "Bechet": ("BECHET", 43.78, 23.95),
    "Bisoca": ("BISOCA", 45.57, 26.72),
    "Bistrița": ("BISTRITA", 47.13, 24.50),
    "Blaj": ("BLAJ", 46.18, 23.92),
    "Boița": ("BOITA", 45.68, 24.25),
    "Borod": ("BOROD", 47.02, 22.48),
    "Botoșani": ("BOTOSANI", 47.75, 26.67),
    "Bozovici": ("BOZOVICI", 44.93, 21.98),
    "Brăila": ("BRAILA", 45.27, 27.97),
    "Brașov": ("BRASOV GHIMBAV", 45.68, 25.53),
    "Bucin": ("BUCIN", 46.73, 25.35),
    "București Afumați": ("BUCURESTI AFUMATI", 44.48, 26.25),
    "București Băneasa": ("BUCURESTI BANEASA", 44.50, 26.08),
    "București Filaret": ("BUCURESTI FILARET", 44.42, 26.10),
    "Buzău": ("BUZAU", 45.15, 26.83),
    "Calafat": ("CALAFAT", 43.99, 22.93),
    "Călărași": ("CALARASI", 44.20, 27.33),
    "Câlimani": ("CALIMANI (RETITIS)", 47.10, 25.22),
    "Câmpeni": ("CAMPENI (BISTRA)", 46.37, 23.05),
    "Câmpina": ("CAMPINA", 45.12, 25.73),
    "Câmpulung Muscel": ("CAMPULUNG MUSCEL", 45.27, 25.05),
    "Caracal": ("CARACAL", 44.12, 24.35),
    "Caransebeș": ("CARANSEBES", 45.42, 22.22),
    "Ceahlău Toaca": ("CEAHLAU TOACA", 46.98, 25.95),
    "Cernavodă": ("CERNAVODA", 44.33, 28.03),
    "Chișineu Criș": ("CHISINEU CRIS", 46.52, 21.52),
    "Cluj-Napoca": ("CLUJ-NAPOCA", 46.77, 23.60),
    "Constanța": ("CONSTANTA", 44.18, 28.63),
    "Corugea": ("CORUGEA", 44.72, 28.47),
    "Cotnari": ("COTNARI", 47.35, 26.97),
    "Craiova": ("CRAIOVA", 44.32, 23.80),
    "Cuntu": ("CUNTU", 45.22, 23.62),
    "Curtea de Argeș": ("CURTEA DE ARGES", 45.13, 24.68),
    "Darabani": ("DARABANI", 48.18, 26.60),
    "Dedulești": ("DEDULESTI-MORARESTI", 45.40, 24.55),
    "Dej": ("DEJ", 47.13, 23.87),
    "Deva": ("DEVA", 45.88, 22.90),
    "Drăgășani": ("DRAGASANI", 44.65, 24.27),
    "Drobeta Turnu Severin": ("DROBETA TURNU SEVERIN", 44.63, 22.65),
    "Dumbrăveni": ("DUMBRAVENI", 46.23, 24.58),
    "Dumbrăvița de Codru": ("DUMBRAVITA DE CODRU", 47.58, 22.37),
    "Făgăraș": ("FAGARAS", 45.85, 24.97),
    "Fetești": ("FETESTI", 44.37, 27.83),
    "Focșani": ("FOCSANI", 45.70, 27.18),
    "Fundata": ("FUNDATA", 45.42, 25.28),
    "Galați": ("GALATI", 45.43, 28.05),
    "Giurgiu": ("GIURGIU", 43.90, 25.97),
    "Gorova": ("GOROVA", 46.55, 26.37),
    "Grivița": ("GRIVITA", 44.07, 27.88),
    "Gura Portiței": ("GURA PORTITEI", 44.70, 29.00),
    "Gurahonț": ("GURAHONT", 46.27, 22.35),
    "Hârsova": ("HARSOVA", 44.68, 27.93),
    "Holod": ("HOLOD", 46.82, 22.13),
    "Huedin": ("HUEDIN", 46.88, 23.02),
    "Iași": ("IASI", 47.17, 27.57),
    "Iezerint": ("IEZERINT", 46.05, 25.98),
    "Întorsura Buzăului": ("INTORSURA BUZAULUI", 45.67, 26.02),
    "Jimbolia": ("JIMBOLIA", 45.78, 20.72),
    "Joseni": ("JOSENI", 46.70, 25.48),
    "Jurilovca": ("JURILOVCA", 44.77, 29.12),
    "Lugoj": ("LUGOJ", 45.68, 21.90),
    "Mahmudia": ("MAHMUDIA", 45.07, 29.07),
    "Mangalia": ("MANGALIA", 43.82, 28.58),
    "Medgidia": ("MEDGIDIA", 44.25, 28.28),
    "Miercurea Ciuc": ("MIERCUREA CIUC", 46.35, 25.80),
    "Moldova Veche": ("MOLDOVA VECHE", 44.73, 21.67),
    "Negrești (Vaslui)": ("NEGRESTI (VASLUI)", 46.83, 27.47),
    "Ocna Șugatag": ("OCNA SUGATAG", 47.77, 23.93),
    "Odorheiul Secuiesc": ("ODORHEIUL SECUIESC", 46.30, 25.30),
    "Oradea": ("ORADEA", 47.07, 21.93),
    "Oravița": ("ORAVITA", 45.03, 21.72),
    "Padeș": ("PADES (APA NEAGRA)", 45.07, 22.72),
    "Păltiniș": ("PALTINIS", 45.65, 23.92),
    "Parâng": ("PARANG", 45.33, 23.55),
    "Pătârlagele": ("PATARLAGE", 45.32, 26.37),
    "Penteleu": ("PENTELEU", 45.52, 26.47),
    "Petroșani": ("PETROSANI", 45.42, 23.37),
    "Piatra Neamț": ("PIATRA NEAMT", 46.93, 26.37),
    "Pitești": ("PITESTI", 44.85, 24.87),
    "Ploiești": ("PLOIESTI", 44.93, 26.02),
    "Poiana Stampei": ("POIANA STAMPEI", 47.32, 25.13),
    "Polovragi": ("POLOVRAGI", 45.18, 23.77),
    "Predeal": ("PREDEAL", 45.50, 25.58),
    "Rădăuți": ("RADAUTI", 47.85, 25.92),
    "Râmnicu Sărat": ("RAMNICU SARAT", 45.38, 27.05),
    "Râmnicu Vâlcea": ("RAMNICU VALCEA", 45.10, 24.37),
    "Rânca": ("RANCA", 45.37, 23.55),
    "Reșița": ("RESITA", 45.30, 21.88),
    "Roman": ("ROMAN", 46.92, 26.93),
    "Roșia Montană": ("ROSIA MONTANA", 46.30, 23.12),
    "Roșiorii de Vede": ("ROSIORII DE VEDE", 44.10, 24.97),
    "Săcuieni": ("SACUIENI", 47.35, 22.08),
    "Sânnicolau Mare": ("SANNICOLAU MARE", 46.07, 20.63),
    "Sârmașu": ("SARMASU", 46.75, 24.18),
    "Satu Mare": ("SATU MARE", 47.80, 22.88),
    "Sebeș": ("SEBES (ALBA)", 45.95, 23.57),
    "Semenic": ("SEMENIC", 45.18, 22.07),
    "Sfântu Gheorghe (Delta)": ("SFANTU GHEORGHE (DELTA)", 44.90, 29.60),
    "Sfântu Gheorghe (Munte)": ("SFANTU GHEORGHE (MUNTE)", 45.87, 25.78),
    "Sibiu": ("SIBIU", 45.80, 24.15),
    "Sighetu Marmației": ("SIGHETUL MARMATIEI", 47.93, 23.90),
    "Sinaia 1500": ("SINAIA 1500", 45.35, 25.55),
    "Siria": ("SIRIA", 46.27, 21.63),
    "Slatina": ("SLATINA", 44.43, 24.37),
    "Slobozia": ("SLOBOZIA", 44.57, 27.37),
    "Stâna de Vale": ("STANA DE VALE", 46.78, 22.68),
    "Ștefănești": ("STEFANESTI STANCA", 47.80, 27.22),
    "Stei": ("STEI (PETRU GROZA)", 46.52, 22.47),
    "Stolnici": ("STOLNICI", 44.55, 24.83),
    "Straja": ("STRAJA", 45.38, 22.73),
    "Suceava": ("SUCEAVA", 47.63, 26.25),
    "Sulina": ("SULINA", 45.15, 29.67),
    "Supuru de Jos": ("SUPURU DE JOS", 47.55, 22.80),
    "Târcuța": ("TARCUTA", 45.95, 22.85),
    "Târgoviște": ("TARGOVISTE", 44.92, 25.45),
    "Târgu Jiu": ("TARGU JIU", 45.03, 23.27),
    "Târgu Lăpuș": ("TARGU LAPUS", 47.45, 23.87),
    "Târgu Logrești": ("TARGU LOGRESTI", 44.88, 23.73),
    "Târgu Mureș": ("TARGU MURES", 46.55, 24.57),
    "Târgu Neamț": ("TARGU NEAMT", 47.20, 26.37),
    "Târgu Ocna": ("TARGU OCNA", 46.28, 26.62),
    "Târgu Secuiesc": ("TARGU SECUIESC", 46.00, 26.13),
    "Târnăveni": ("TARNAVENI (BOBOHALMA)", 46.33, 24.27),
    "Tebea": ("TEBEA", 46.07, 22.87),
    "Tecuci": ("TECUCI", 45.85, 27.43),
    "Timișoara": ("TIMISOARA", 45.75, 21.23),
    "Titu": ("TITU", 44.65, 25.58),
    "Toplița": ("TOPLITA", 46.92, 25.35),
    "Tulcea": ("TULCEA", 45.17, 28.80),
    "Turda": ("TURDA", 46.57, 23.78),
    "Turnu Măgurele": ("TURNU MAGURELE", 43.75, 24.88),
    "Urziceni": ("URZICENI", 44.72, 26.63),
    "Varadia de Mureș": ("VARADIA DE MURES", 45.95, 21.57),
    "Vârful Omu": ("VARFUL OMU", 45.45, 25.45),
    "Vaslui": ("VASLUI", 46.63, 27.73),
    "Videle": ("VIDELE", 44.28, 25.52),
    "Vlădeasa 1800": ("VLADEASA 1800", 46.75, 22.82),
    "Voinești": ("VOINEA", 45.00, 25.30),
    "Zalău": ("ZALAU", 47.18, 23.05),
    "Zimnicea": ("ZIMNICEA", 43.65, 25.37),
}

# Mapare oras -> judet (pentru filtrarea alertelor ANM)
CITY_COUNTY = {
    "Adamclisi": "Constanta",
    "Adjud": "Vrancea",
    "Alba Iulia": "Alba",
    "Alexandria": "Teleorman",
    "Amzacea": "Constanta",
    "Arad": "Arad",
    "Bacău": "Bacau",
    "Bacles": "Valcea",
    "Baia Mare": "Maramures",
    "Băile Herculane": "Caras-Severin",
    "Băilești": "Dolj",
    "Băișoara": "Cluj",
    "Balea Lac": "Sibiu",
    "Banloc": "Timis",
    "Baraolt": "Covasna",
    "Bârlad": "Vaslui",
    "Barnova": "Iasi",
    "Batoș": "Mures",
    "Bechet": "Dolj",
    "Bisoca": "Buzau",
    "Bistrița": "Bistrita-Nasaud",
    "Blaj": "Alba",
    "Boița": "Sibiu",
    "Borod": "Bihor",
    "Botoșani": "Botosani",
    "Bozovici": "Caras-Severin",
    "Brăila": "Braila",
    "Brașov": "Brasov",
    "Bucin": "Harghita",
    "București Afumați": "Ilfov",
    "București Băneasa": "Municipiul Bucuresti",
    "București Filaret": "Municipiul Bucuresti",
    "Buzău": "Buzau",
    "Calafat": "Dolj",
    "Călărași": "Calarasi",
    "Câlimani": "Mures",
    "Câmpeni": "Alba",
    "Câmpina": "Prahova",
    "Câmpulung Muscel": "Arges",
    "Caracal": "Olt",
    "Caransebeș": "Caras-Severin",
    "Ceahlău Toaca": "Neamt",
    "Cernavodă": "Constanta",
    "Chișineu Criș": "Arad",
    "Cluj-Napoca": "Cluj",
    "Constanța": "Constanta",
    "Corugea": "Tulcea",
    "Cotnari": "Iasi",
    "Craiova": "Dolj",
    "Cuntu": "Valcea",
    "Curtea de Argeș": "Arges",
    "Darabani": "Botosani",
    "Dedulești": "Arges",
    "Dej": "Cluj",
    "Deva": "Hunedoara",
    "Drăgășani": "Valcea",
    "Drobeta Turnu Severin": "Mehedinti",
    "Dumbrăveni": "Sibiu",
    "Dumbrăvița de Codru": "Satu Mare",
    "Făgăraș": "Brasov",
    "Fetești": "Ialomita",
    "Focșani": "Vrancea",
    "Fundata": "Brasov",
    "Galați": "Galati",
    "Giurgiu": "Giurgiu",
    "Gorova": "Bacau",
    "Grivița": "Ialomita",
    "Gura Portiței": "Tulcea",
    "Gurahonț": "Arad",
    "Hârsova": "Constanta",
    "Holod": "Bihor",
    "Huedin": "Cluj",
    "Iași": "Iasi",
    "Iezerint": "Covasna",
    "Întorsura Buzăului": "Covasna",
    "Jimbolia": "Timis",
    "Joseni": "Harghita",
    "Jurilovca": "Tulcea",
    "Lugoj": "Timis",
    "Mahmudia": "Tulcea",
    "Mangalia": "Constanta",
    "Medgidia": "Constanta",
    "Miercurea Ciuc": "Harghita",
    "Moldova Veche": "Caras-Severin",
    "Negrești (Vaslui)": "Vaslui",
    "Ocna Șugatag": "Maramures",
    "Odorheiul Secuiesc": "Harghita",
    "Oradea": "Bihor",
    "Oravița": "Caras-Severin",
    "Padeș": "Gorj",
    "Păltiniș": "Sibiu",
    "Parâng": "Gorj",
    "Pătârlagele": "Buzau",
    "Penteleu": "Buzau",
    "Petroșani": "Hunedoara",
    "Piatra Neamț": "Neamt",
    "Pitești": "Arges",
    "Ploiești": "Prahova",
    "Poiana Stampei": "Suceava",
    "Polovragi": "Gorj",
    "Predeal": "Brasov",
    "Rădăuți": "Suceava",
    "Râmnicu Sărat": "Buzau",
    "Râmnicu Vâlcea": "Valcea",
    "Rânca": "Gorj",
    "Reșița": "Caras-Severin",
    "Roman": "Neamt",
    "Roșia Montană": "Alba",
    "Roșiorii de Vede": "Teleorman",
    "Săcuieni": "Bihor",
    "Sânnicolau Mare": "Timis",
    "Sârmașu": "Mures",
    "Satu Mare": "Satu Mare",
    "Sebeș": "Alba",
    "Semenic": "Caras-Severin",
    "Sfântu Gheorghe (Delta)": "Tulcea",
    "Sfântu Gheorghe (Munte)": "Covasna",
    "Sibiu": "Sibiu",
    "Sighetu Marmației": "Maramures",
    "Sinaia 1500": "Prahova",
    "Siria": "Arad",
    "Slatina": "Olt",
    "Slobozia": "Ialomita",
    "Stâna de Vale": "Bihor",
    "Ștefănești": "Botosani",
    "Stei": "Bihor",
    "Stolnici": "Arges",
    "Straja": "Caras-Severin",
    "Suceava": "Suceava",
    "Sulina": "Tulcea",
    "Supuru de Jos": "Satu Mare",
    "Târcuța": "Caras-Severin",
    "Târgoviște": "Dambovita",
    "Târgu Jiu": "Gorj",
    "Târgu Lăpuș": "Maramures",
    "Târgu Logrești": "Gorj",
    "Târgu Mureș": "Mures",
    "Târgu Neamț": "Neamt",
    "Târgu Ocna": "Bacau",
    "Târgu Secuiesc": "Covasna",
    "Târnăveni": "Mures",
    "Tebea": "Hunedoara",
    "Tecuci": "Galati",
    "Timișoara": "Timis",
    "Titu": "Dambovita",
    "Toplița": "Harghita",
    "Tulcea": "Tulcea",
    "Turda": "Cluj",
    "Turnu Măgurele": "Teleorman",
    "Urziceni": "Ialomita",
    "Varadia de Mureș": "Caras-Severin",
    "Vârful Omu": "Prahova",
    "Vaslui": "Vaslui",
    "Videle": "Teleorman",
    "Vlădeasa 1800": "Cluj",
    "Voinești": "Dambovita",
    "Zalău": "Salaj",
    "Zimnicea": "Teleorman",
}

# Mapare judet -> cod ANM din XML (folosit pentru filtrarea alertelor)
COUNTY_CODES = {
    "Alba": "AB",
    "Arad": "AR",
    "Arges": "AG",
    "Bacau": "BC",
    "Bihor": "BH",
    "Bistrita-Nasaud": "BN",
    "Botosani": "BT",
    "Brasov": "BV",
    "Braila": "BR",
    "Buzau": "BZ",
    "Caras-Severin": "CS",
    "Calarasi": "CL",
    "Cluj": "CJ",
    "Constanta": "CT",
    "Covasna": "CV",
    "Dambovita": "DB",
    "Dolj": "DJ",
    "Galati": "GL",
    "Giurgiu": "GR",
    "Gorj": "GJ",
    "Harghita": "HR",
    "Hunedoara": "HD",
    "Ialomita": "IL",
    "Iasi": "IS",
    "Ilfov": "IF",
    "Maramures": "MM",
    "Mehedinti": "MH",
    "Mures": "MS",
    "Neamt": "NT",
    "Olt": "OT",
    "Prahova": "PH",
    "Satu Mare": "SM",
    "Salaj": "SJ",
    "Sibiu": "SB",
    "Suceava": "SV",
    "Teleorman": "TR",
    "Timis": "TM",
    "Tulcea": "TL",
    "Vaslui": "VS",
    "Valcea": "VL",
    "Vrancea": "VN",
    "Municipiul Bucuresti": "B",
}
