"""Constante pentru Info Meteo Romania."""

DOMAIN = "info_meteo_romania"
SCAN_INTERVAL = 30  # minute

# URL-uri API ANM
WEATHER_API_URL = "https://www.meteoromania.ro/wp-json/meteoapi/v2/starea-vremii"
ALERTS_XML_URL = "https://www.meteoromania.ro/avertizari-xml.php"
NOWCASTING_XML_URL = "https://www.meteoromania.ro/avertizari-nowcasting-xml.php"

# Cheia = ce vede utilizatorul in meniu
# Valoarea = numele EXACT din campul "nume" din API-ul ANM
CITIES = {
    "Adamclisi": "ADAMCLISI",
    "Adjud": "ADJUD",
    "Alba Iulia": "ALBA IULIA",
    "Alexandria": "ALEXANDRIA",
    "Amzacea": "AMZACEA",
    "Arad": "ARAD",
    "Bacău": "BACAU",
    "Bacles": "BACLES",
    "Baia Mare": "BAIA MARE",
    "Băile Herculane": "BAILE HERCULANE",
    "Băilești": "BAILESTI",
    "Băișoara": "BAISOARA",
    "Balea Lac": "BALEA LAC",
    "Banloc": "BANLOC",
    "Baraolt": "BARAOLT",
    "Bârlad": "BARLAD",
    "Barnova": "BARNOVA (RADAR)",
    "Batoș": "BATOS",
    "Bechet": "BECHET",
    "Bisoca": "BISOCA",
    "Bistrița": "BISTRITA",
    "Blaj": "BLAJ",
    "Boița": "BOITA",
    "Borod": "BOROD",
    "Botoșani": "BOTOSANI",
    "Bozovici": "BOZOVICI",
    "Brăila": "BRAILA",
    "Brașov": "BRASOV GHIMBAV",
    "Bucin": "BUCIN",
    "București Afumați": "BUCURESTI AFUMATI",
    "București Băneasa": "BUCURESTI BANEASA",
    "București Filaret": "BUCURESTI FILARET",
    "Buzău": "BUZAU",
    "Calafat": "CALAFAT",
    "Călărași": "CALARASI",
    "Câlimani": "CALIMANI (RETITIS)",
    "Câmpeni": "CAMPENI (BISTRA)",
    "Câmpina": "CAMPINA",
    "Câmpulung Muscel": "CAMPULUNG MUSCEL",
    "Caracal": "CARACAL",
    "Caransebeș": "CARANSEBES",
    "Ceahlău Toaca": "CEAHLAU TOACA",
    "Cernavodă": "CERNAVODA",
    "Chișineu Criș": "CHISINEU CRIS",
    "Cluj-Napoca": "CLUJ-NAPOCA",
    "Constanța": "CONSTANTA",
    "Corugea": "CORUGEA",
    "Cotnari": "COTNARI",
    "Craiova": "CRAIOVA",
    "Cuntu": "CUNTU",
    "Curtea de Argeș": "CURTEA DE ARGES",
    "Darabani": "DARABANI",
    "Dedulești": "DEDULESTI-MORARESTI",
    "Dej": "DEJ",
    "Deva": "DEVA",
    "Drăgășani": "DRAGASANI",
    "Drobeta Turnu Severin": "DROBETA TURNU SEVERIN",
    "Dumbrăveni": "DUMBRAVENI",
    "Dumbrăvița de Codru": "DUMBRAVITA DE CODRU",
    "Făgăraș": "FAGARAS",
    "Fetești": "FETESTI",
    "Focșani": "FOCSANI",
    "Fundata": "FUNDATA",
    "Galați": "GALATI",
    "Giurgiu": "GIURGIU",
    "Gorova": "GOROVA",
    "Grivița": "GRIVITA",
    "Gura Portiței": "GURA PORTITEI",
    "Gurahonț": "GURAHONT",
    "Hârsova": "HARSOVA",
    "Holod": "HOLOD",
    "Huedin": "HUEDIN",
    "Iași": "IASI",
    "Iezerint": "IEZERINT",
    "Întorsura Buzăului": "INTORSURA BUZAULUI",
    "Jimbolia": "JIMBOLIA",
    "Joseni": "JOSENI",
    "Jurilovca": "JURILOVCA",
    "Lacul": "LACAUT",
    "Lugoj": "LUGOJ",
    "Mahmudia": "MAHMUDIA",
    "Mangalia": "MANGALIA",
    "Medgidia": "MEDGIDIA",
    "Miercurea Ciuc": "MIERCUREA CIUC",
    "Moldova Veche": "MOLDOVA VECHE",
    "Negrești (Vaslui)": "NEGRESTI (VASLUI)",
    "Ocna Șugatag": "OCNA SUGATAG",
    "Odorheiul Secuiesc": "ODORHEIUL SECUIESC",
    "Oltenița": "OLTENITA",
    "Oradea": "ORADEA",
    "Oravița": "ORAVITA",
    "Padeș": "PADES (APA NEAGRA)",
    "Păltiniș": "PALTINIS",
    "Parâng": "PARANG",
    "Pătârlagele": "PATARLAGE",
    "Penteleu": "PENTELEU",
    "Petroșani": "PETROSANI",
    "Piatra Neamț": "PIATRA NEAMT",
    "Pitești": "PITESTI",
    "Ploiești": "PLOIESTI",
    "Poiana Stampei": "POIANA STAMPEI",
    "Polovragi": "POLOVRAGI",
    "Predeal": "PREDEAL",
    "Rădăuți": "RADAUTI",
    "Râmnicu Sărat": "RAMNICU SARAT",
    "Râmnicu Vâlcea": "RAMNICU VALCEA",
    "Rânca": "RANCA",
    "Reșița": "RESITA",
    "Roman": "ROMAN",
    "Roșia Montană": "ROSIA MONTANA",
    "Roșiorii de Vede": "ROSIORII DE VEDE",
    "Săcuieni": "SACUIENI",
    "Sânnicolau Mare": "SANNICOLAU MARE",
    "Sârmașu": "SARMASU",
    "Satu Mare": "SATU MARE",
    "Sebeș": "SEBES (ALBA)",
    "Semenic": "SEMENIC",
    "Sfântu Gheorghe (Delta)": "SFANTU GHEORGHE (DELTA)",
    "Sfântu Gheorghe (Munte)": "SFANTU GHEORGHE (MUNTE)",
    "Sibiu": "SIBIU",
    "Sighetu Marmației": "SIGHETUL MARMATIEI",
    "Sinaia 1500": "SINAIA 1500",
    "Siria": "SIRIA",
    "Slatina": "SLATINA",
    "Slobozia": "SLOBOZIA",
    "Stâna de Vale": "STANA DE VALE",
    "Ștefănești": "STEFANESTI STANCA",
    "Stei": "STEI (PETRU GROZA)",
    "Stolnici": "STOLNICI",
    "Straja": "STRAJA",
    "Suceava": "SUCEAVA",
    "Sulina": "SULINA",
    "Supuru de Jos": "SUPURU DE JOS",
    "Târcuța": "TARCUTA",
    "Târgoviște": "TARGOVISTE",
    "Târgu Jiu": "TARGU JIU",
    "Târgu Lăpuș": "TARGU LAPUS",
    "Târgu Logrești": "TARGU LOGRESTI",
    "Târgu Mureș": "TARGU MURES",
    "Târgu Neamț": "TARGU NEAMT",
    "Târgu Ocna": "TARGU OCNA",
    "Târgu Secuiesc": "TARGU SECUIESC",
    "Târnăveni": "TARNAVENI (BOBOHALMA)",
    "Tebea": "TEBEA",
    "Tecuci": "TECUCI",
    "Timișoara": "TIMISOARA",
    "Titu": "TITU",
    "Toplița": "TOPLITA",
    "Tulcea": "TULCEA",
    "Turda": "TURDA",
    "Turnu Măgurele": "TURNU MAGURELE",
    "Urziceni": "URZICENI",
    "Varadia de Mureș": "VARADIA DE MURES",
    "Vârful Omu": "VARFUL OMU",
    "Vaslui": "VASLUI",
    "Videle": "VIDELE",
    "Vlădeasa 1800": "VLADEASA 1800",
    "Voinești": "VOINEA",
    "Zalău": "ZALAU",
    "Zimnicea": "ZIMNICEA",
}
